excerpt_separator: <!--more-->
highlighter: rouge
markdown: kramdown
url: http://seanosaur.github.io
title: Sean Oldham
paginate: 5
gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts
